### ISSUE TITLE
SL-Infinity Controller issues...

### ISSUE THREAD

**Issue by groooooooooooot** [EightB1ts/FanControl.LianLi#1]
Thank you for this.  

I am using the SL-Inifinity Controller (pid a102) with version 1.4 (latest) BIOS with the FanControl.LianLi.Plugin.dll.  L-Connect is not running at all in the background.

There are definite signs of life, the controller channels are detected and showing up in FanControl.  They do respond to manual speed adjustments so they are receiving commands from FanControl.  However, they dont hold the speed that is being set... i.e. they will respond initially to the setting but then after a few seconds (5-10ish) the fan speeds will ramp back to maximum speed.  If I readjust the sliders the fans will respond again, temporarily, and then after 5-10 seconds return to max speed.   Very odd.

Setting to a curve doesnt seem to react at all, meaning if I set to a sensor curve (cpu temp for example), the fans simply run at max speed.

So FYI, I do have an extra controller that I probably would be willing to ship out to you but before going that route is it possible to make any headway/progress via debug or logging files?  I would be happy to capture any logging information for you if that's an option...

**Comment by groooooooooooot** [comment]
I just realized the controller by itself probably wont help, you need a fan PLUS the controller I presume...

**Comment by EightB1ts** [comment]
What is their speed setting in L-Connect? One thing to check is that PWM mode isn’t enabled.

Seems like a packet or two needs to be adjusted for that particular model. Testing can be done through Wireshark, but L-Connect is a bit noisy and filtering through packets is a bit difficult.

Let’s try this, I’ll put together an executable tomorrow capable of sending test packets and basically you’d run that while Wireshark runs. 

In the meantime, go ahead and install Wireshark, while installing make sure you check usbpcap is installed along with it (it’ll ask you). Then, you’ll need to figure out which USB hub your controller is on. For me it was USBPcap 1.

Check each hub, then check for packets where the “Info” column is named “GET_DESCRIPTOR Response DEVICE”. Click on it and confirm in the packet information (bottom left) the name of the device. 

Quick video showing this: https://youtube.com/watch?v=EfkC7kmIMt8

**Comment by groooooooooooot** [comment]
The fans are normally running at 875-950 in L-Connect.  PWM is definitely disabled.  Interesting you mention that though because if I enable PWM in L-Connect the fans also spin up to max speed.  I always attributed this to some kind of issue between L-Connect, the controller and the motherboard bios (I dont trust L-Connect basically...)

The RPM values are visible in FanControl.  I can watch them adjust when I manually set them and then I seem them fluctuate a bit and then climb back to max span speed (~2100 rpm).

I can try wireshark though i am no packet sniffing expert :)

For my curiosity, your SL controller/fans are working perfectly now via FanControl?  Ie  respond to manual control as well as defined curves?

**Comment by EightB1ts** [comment]
Gotcha. Yes, they do work normally. 

I am considering changing my approach on the communication protocols with the controllers. L-Connect 2 communicates via the same methodology I am using, but L-Connect 3 communicates as an HID device. L-Connect is an ElectronJS app which made it relatively straightforward to dump the source JavaScript (it is minified however). I identified where in the minified file it’s sending commands to the various controllers. I may be able to add support for all controllers just by looking at this code.

**Comment by EightB1ts** [comment]
I've updated this to use the HID communication protocol and added support for all known Lian Li controllers. This should perform better. Could you let me know if this latest release works for you?
https://github.com/EightB1ts/FanControl.LianLi/releases/tag/v1.0.0-beta.3

**Comment by groooooooooooot** [comment]
early results look very promising... let me bang away on it more though.  Look good so far!

**Comment by groooooooooooot** [comment]
I think this is a winner.  Both curve response and manual control seems to work great.  Nice job!  I would like to buy you a couple coffees!

**Comment by EightB1ts** [comment]
Thank you very much! I’ll mark this device as supported 😄
