### ISSUE TITLE
No Dispose?

### ISSUE THREAD

**Issue by Rem0o** [EightB1ts/FanControl.LianLi#2]
Took a quick look, and saw that the Close() method in the plugin, which is the mirror of Initialize(), doesn't dispose/clears anything.

The HIDDevice internal class opens a stream and doesn't dispose it AFAIK.   Maybe take a quick look round the stuff that should be disposed, and route all of this back to the Plugin.Close() method.   There isn't a need for the dispose pattern in that class by the way.  Close will get called when the app exits.

**Comment by EightB1ts** [comment]
Thanks a bunch for checking! I now dispose open streams, added in this commit: 
https://github.com/EightB1ts/FanControl.LianLi/commit/e7203917524dd68f812e68cd0746786b20c9e465

Also got rid of that dispose pattern you mentioned.
