### ISSUE TITLE
UNI SLv2 - Control works, Incorrect RPM values

### ISSUE THREAD

**Issue by justinhippen** [EightB1ts/FanControl.LianLi#3]
FYI - FanControl + Uni SLv2 controller works to control fan speeds on both SLv2 and ALv2 fans. RPM readings are wrong.

FanControl
![image](https://github.com/EightB1ts/FanControl.LianLi/assets/20194814/bc8075d5-627a-4c93-a70a-c8454c4af5ab)

Device Info
![image](https://github.com/EightB1ts/FanControl.LianLi/assets/20194814/fa9be8f5-1bce-461c-b654-669237e70d9b)

**Comment by EightB1ts** [comment]
Hi There, 

Thanks for sharing! I'll take a look into this and see if it can be addressed without a packet capture using wireshark.

**Comment by EightB1ts** [comment]
Would you be able to run a packet capture for me so I can determine the issue? It shouldn't take too long.  If you can, please follow these instructions: 

1. Make sure FanControl and L-Connect is closed 
2. Install [Wireshark](https://www.wireshark.org/download.html), while installing make sure you check usbpcap is installed along with it (it’ll ask you).
3. Then, you’ll need to figure out which USB hub your controller is on. Check each hub, then check for packets where the “Info” column is named “GET_DESCRIPTOR Response DEVICE”. Click on it and confirm in the packet information (bottom left) the name of the device. Quick video showing this: https://youtube.com/watch?v=EfkC7kmIMt8
4. Open FanControl and let Wireshark capture the packets for 15-30 seconds
5. Hit Red stop button in Wireshark (top left) then File -> Export Specified Packets

Then upload the file here.

**Comment by justinhippen** [comment]
The UNI Hun is at usb.device_address == 2.

[LianLi.pcapng.gz](https://github.com/EightB1ts/FanControl.LianLi/files/11782509/LianLi.pcapng.gz)

**Comment by EightB1ts** [comment]
Thanks for that! Could you try this build? I believe this fixes the issue. 
[FanControl.LianLiPlugin.zip](https://github.com/EightB1ts/FanControl.LianLi/files/11785034/FanControl.LianLiPlugin.zip)

**Comment by justinhippen** [comment]
Works good!

**Comment by EightB1ts** [comment]
Great! I have published a new Beta v5: https://github.com/EightB1ts/FanControl.LianLi/releases/tag/v1.0.0-beta.5
