### ISSUE TITLE
Plugin Crashing FanControl when Launched

### ISSUE THREAD

**Issue by Wolphin5** [EightB1ts/FanControl.LianLi#4]
Problem Signature 03:	b14a05cf
I have the AL fan controller and wanted to see if it worked.
When I try to run FanControl with the plugin, FanControl crashes immediately.  I have tried both plugins.  Please let me know what sort of help you need to diagnose the issue.

I have seen this issue with 159 and 160 of the fan control, and Windows 10 Pro.
`
FanControl Error:
2023-06-13 15:36:02: Unhandled exception in FanControl v159.0.0.0
2023-06-13 15:36:02: System.InvalidOperationException: HidSharp RegisterClass failed.
   at HidSharp.Platform.Windows.WinHidManager.Run(Action readyCallback)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

Reliability Report shows the application crashing on load:
Problem signature
Problem Event Name:	CLR20r3
Problem Signature 01:	FanControl.exe
Problem Signature 02:	159.0.0.0
Problem Signature 03:	b14a05cf
Problem Signature 04:	HidSharp
Problem Signature 05:	2.1.0.0
Problem Signature 06:	5ccde7b9
Problem Signature 07:	689
Problem Signature 08:	0
Problem Signature 09:	System.InvalidOperationException
OS Version:	10.0.19045.2.0.0.256.48
Locale ID:	4105
Additional Information 1:	e96e
Additional Information 2:	e96e5edf0e41a0014ff7903826543795
Additional Information 3:	cf08
Additional Information 4:	cf08e5e54967910ddf3c6941db692465

Extra information about the problem
Bucket ID:	fe77c5e3e7eb47eb7b1311c72cc57bcb (1950922610728860619)
`
`Description
Faulting Application Path:	D:\Cloud Storage\OneDrive\Programs\FanControl\FanControl.exe

Problem signature
Problem Event Name:	CLR20r3
Problem Signature 01:	FanControl.exe
Problem Signature 02:	160.0.0.0
Problem Signature 03:	a1cb1214
Problem Signature 04:	HidSharp
Problem Signature 05:	2.1.0.0
Problem Signature 06:	5ccde7b9
Problem Signature 07:	689
Problem Signature 08:	0
Problem Signature 09:	System.InvalidOperationException
OS Version:	10.0.19045.2.0.0.256.48
Locale ID:	4105
Additional Information 1:	e96e
Additional Information 2:	e96e5edf0e41a0014ff7903826543795
Additional Information 3:	f63f
Additional Information 4:	f63fd1fde7630f5bbca64d4e5c0b9e8e

Extra information about the problem
Bucket ID:	e7448f811e7098729ce242e6f83c56ef (2081299537573205743)
`

I have LianLi-UNI FAN-AL-v1.7 but it currently is not connected.  Even deleting the device from my system, so it isn't there, I still have it crashing FanControl when either plugin is installed.  I do not have any other plugin installed.

Asus Crosshair VIII Hero Wifi Motherboard.

Please let me know of any other testing or information you need.

**Comment by EightB1ts** [comment]
Hello, can you share the log file located in the directory of the FanControl exe?

**Comment by Wolphin5** [comment]
[log.txt](https://github.com/EightB1ts/FanControl.LianLi/files/11779690/log.txt)
Log attached

**Comment by EightB1ts** [comment]
Could you try this build and see if it works? Note: This will require FanControl .NET v7
[FanControl.LianLiPlugin.zip](https://github.com/EightB1ts/FanControl.LianLi/files/11779767/FanControl.LianLiPlugin.zip)

**Comment by Wolphin5** [comment]
Not sure what I was running, but suspect it wasn't, as didn't have .NET 7 installed.
Downloaded (From Microsoft) and installed .NET framework 7 (x86 and x64)
Downloaded the .NET 7 version of FanControl, and it loads correctly, and updated it to 160.
Loaded my existing configuration file.
Existed and confirmed FanControl was not running
Installed the supplied file and FanControl loaded, but did not show the plugin loading
Exited FanControl and tried to relaunch; crashed.
Tried with the Beta 4 (no RGB); crashed
Removed file, Fan Control loaded.

Adding the new log file.
[log.txt](https://github.com/EightB1ts/FanControl.LianLi/files/11779834/log.txt)

**Comment by Wolphin5** [comment]
Note: I currently don't have the controller attached, as I currently have the fans being controlled directly from my MB

**Comment by EightB1ts** [comment]
Ok, thanks. The controller being attached is irrelevant in this case. I believe the issue pertains to your setup, not sure what the exact issue is without the Visual Studio debugger in front of me. Shot in the dark here, but have all your tests been under D:\Cloud Storage\OneDrive\Programs? Have you tried running it on your main disk? And running FanControl as administrator?

Next steps would either A) Take the source code, install Visual Studio, build a Debug build of the plugin. Then attach to the FanControl.exe process. or B) Try on a clean install of Windows

**Comment by Wolphin5** [comment]
I didn't think having the controller installed was an issue, but wanted to make sure you were aware of it.
I have tried moving the FanControl directory to C: and it didn't do anything.
The program needs admin when it is launched.

My Visual Studio is out of date.  I'll update and try a debug load of it.

I am not interested in doing a clean OS build on this system at this time.  The plugin isn't that valuable to do that.  With the amount of software and configurations I have, it would take me 2-3 days to restore it to my functionality.

**Comment by Wolphin5** [comment]
I have never done this sort of debugging... I mostly have done tech support.  Not sure how to get this debugging going.  Built it, and when it launches, gives me an error of:
![image](https://github.com/EightB1ts/FanControl.LianLi/assets/44385601/637728fe-61f2-4c8a-b0d7-04c02c05fb32)

Have not been able to see the issue.  Under Application, I am seeing .NET Framework 4.8 listed, not a .NET Core.  Am I missing something to build it from my VisualStudio install?
![image](https://github.com/EightB1ts/FanControl.LianLi/assets/44385601/7a8a0a05-2699-4993-a1eb-00cee32ec406)

**Comment by EightB1ts** [comment]
If you’d like, I can also remote into your machine and debug remotely if you’re comfortable with that. Just shoot me an email me@cameronhalter.com. I’ll revisit the tomorrow.

**Comment by EightB1ts** [comment]
Sorry for the delay, I was able to get this resolved and is now part of the final v1 release located here:
