### ISSUE TITLE
Plugin does not load

### ISSUE THREAD

**Issue by fshelton79** [EightB1ts/FanControl.LianLi#6]
![image](https://github.com/EightB1ts/FanControl.LianLi/assets/33131794/2952ed75-2cc4-4dc3-9d26-58569339e712)

**Comment by EightB1ts** [comment]
Does FanControl provide an error for you? Please provide a copy of the log file located in the same directory as the FanControl executable.

**Comment by fshelton79** [comment]
[log.txt](https://github.com/EightB1ts/FanControl.LianLi/files/11990893/log.txt)

**Comment by EightB1ts** [comment]
> 7/7/2023 12:55:33 PM: Failed to load plugin FanControl.LianLiPlugin.dll. Make sure the plugin's dll is unblocked in its properties.

See: https://github.com/Rem0o/FanControl.Releases/issues/724

Right click the DLL-->Properties and unblock it.
